### ISSUE TITLE
Writing a book

### ISSUE THREAD

**Issue by alexec** [daluu/AutoItDriverServer#6]
Hi,

I'm involved in writing a book on WebDriver for Manning. We're looking for another coauthor. Do you think you might be interested in getting involved?

Alex

**Comment by kishor9096** [comment]
I am interested let me know how I can help in this regard.

Regards
Kishor Srivastava

**Comment by daluu** [comment]
Alex,

I don't mind getting involved. Not sure about being a "co-author" though. I've been a reviewer for book projects from Packt Publishing in the past.

Have you reached out to others as well? I know some people that would make good co-authors if they wanted to get involved:

http://davehaeffner.com
Alister Scott at http://watirmelon.com/about/

Regards,
David

**Comment by alexec** [comment]
Thanks! I'll give them a look as I've read them before and like what they
do!
